# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: mixed-line-ending
        args: ["--fix", "lf"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs
        args: [--whitespaces-count, "2"]
  - repo: https://github.com/mattlqx/pre-commit-search-and-replace
    rev: v1.1.8
    hooks:
      - id: search-and-replace
        stages: [commit-msg, pre-commit]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.20.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        args: ["--verbose"]
        verbose: true
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-2
    hooks:
      - id: shfmt
        args: ["--space-redirects", "--case-indent", "--indent", "2"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
  #  - repo: https://github.com/google/yamlfmt
  #    rev: v0.15.0
  #    hooks:
  #      - id: yamlfmt
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.19.0
    hooks:
      - id: eslint
        types: [yaml]
        args: ["--fix"]
        additional_dependencies:
          - eslint-plugin-yml@1.16.0
          - eslint@9.19.0

# files: \.ya?ml$
